version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5050:5000"  # Alterado para a porta 5050
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgres://usuario_do_banco:senha_do_banco@db:5432/nome_do_banco
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "4040:5173"  # Alterado para a porta 4040
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - "3040:5432"  # Alterado para a porta 3040
    environment:
      POSTGRES_DB: nome_do_banco
      POSTGRES_USER: usuario_do_banco
      POSTGRES_PASSWORD: senha_do_banco
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
