version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "50:5000"  
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgres://usuario_do_banco:senha_do_banco@db:5432/nome_do_banco
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app/frontend
      - node_modules_volume:/app/frontend/node_modules
    command: sh -c "yarn install && yarn dev --host" #Instala node_modules e roda o programa na web
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - "3040:5432" 
    environment:
      POSTGRES_DB: nome_do_banco
      POSTGRES_USER: usuario_do_banco
      POSTGRES_PASSWORD: senha_do_banco
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules_volume: #Ao definir, estamos salvando para que fique persistente.