version: '3.8'

services:
  backend:
    container_name: pythonbc
    build: ./backend
    ports:
      - "50:5000"  
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgres://usuario_do_banco:senha_do_banco@db:5432/nome_do_banco
    depends_on:
      - db

  frontend:
    container_name: reactft
    build: ./frontend
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - UPLOAD_FOLDER=/app/uploads
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app/frontend
      - ./backend/uploads:/app/uploads
      - node_modules_volume:/app/frontend/node_modules
    command: sh -c "yarn install && yarn dev --host"
    depends_on:
      - backend

  db:
    container_name: postgresbd
    image: postgres:15
    ports:
      - "3040:5432" 
    environment:
      POSTGRES_DB: meau_pets
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # Ao inicializar o docker pela primeira vez: cria as tabelas definidas em init-db.sql

volumes:
  postgres_data:
  node_modules_volume: #Ao definir, estamos salvando para que fique persistente.